### ISSUE TITLE
Fixes to sending credit directly

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#158]
It's possible to send credit to another user 'directly' (i.e. without making a purchase request for one of their Offers via the Marketplace and Cart) by finding their profile in the Members directory and filling in the fields under 'Send pollen'.

This functionality works as it should i.e.: balance limits are enforced, and if the transfer is valid, the recipient is notified and can approve or decline to complete the transaction. 

However, there are a few fixes needed to make this more user-friendly:

- [x] After pressing the 'Send' button on a valid transaction, the sender sees a more-or-less blank screen with no feedback, and has to manually refresh the page in order to reload the view of the recipient member's profile. Consistent with #92, an acknowledgement pop-up should appear with header text reading 'Transfer request sent', main text reading 'Thank you for your transfer request. `recipient username` has been notified, and you will receive a notification as soon as they have either approved or declined the request', and an 'Okay' button to close. After closing via the 'Okay' button, the page should auto-refresh on the recipient member's profile.
- [ ] The recipient sees a notification which reads '`sender username` has sent`transfer amount` `credit unit`. Go to My account to approve or decline'. This should be updated to '`sender username` has made a transfer request for `transfer amount` `credit unit`. Go to My account to approve or decline.'
- [ ] If recipient approves, notification to sender reads '`recipient user` has approved your purchase request. Go to My account to download the invoice.' This should be updated to '`recipient user` has approved your transfer request. Go to My account to download the invoice.'
- [ ] If recipient declines, notification to sender reads '`recipient user` has declined your purchase request.' This should be updated to '`recipient user` has declined your transfer request.'
- [ ] If the transfer would violate the sender's negative credit limit, it is not progressed (the recipient doesn't get a notification), but there is no feedback to the sender. Consistent with #91, a pop-up should appear with header text reading 'Insufficient credit', main text reading 'You do not have enough credit to request this transfer, as the amount is `transfer amount` `credit unit` and your available credit is `available credit` `credit unit`', and an 'Okay' button to close. After closing via the 'Okay' button, the page should auto-refresh on the recipient member's profile.
- [x] If the transfer would violate the recipient's positive credit limit, it is not progressed (the recipient doesn't get a notification), but there is no feedback to the sender. Consistent with #86, a pop-up should appear with header text reading 'Recipient balance too high', main text reading 'This transfer request cannot be completed, as it would take `recipient username` beyond their positive credit limit. `recipient username` has been notified, but please consider following up with them about your intended transfer', and an 'Okay' button to close. After closing via the 'Okay' button, the page should auto-refresh on the recipient member's profile. Consistent with #88, the recipient should also get a notification reading '`sender username` initiated a transfer request with you for `transfer amount` `credit unit`, but this could not be processed as it would have taken you beyond your positive credit limit by `amount` `credit unit`. Please consider following up with `sender username` about their intended transfer' (NB the `amount` calculation may not have been implemented yet in #88 - check).
- [x] Outstanding transfer requests should appear for the sender under My account -> Pending Purchases.

**Comment by tfwoodroofMCS** [comment]
Mostly working fine, except I think I've managed to break it by trying to make a transfer that would violated the sender's negative limit:

- I tried to send 600 pollen, despite having only 500 available. The app did not give any feedback, i.e. it seems that the fifth point above has not been implemented.
- I then tried to send 200 pollen, and got the following message (which not only shouldn't be triggered, but doesn't make sense as the 'total price' is stated to be less than the 'available credit'):

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/3d97949a-a53f-44bf-a4f2-4ec0c3bbac54)

**Comment by tfwoodroofMCS** [comment]
Negative limit enforcement now working as expected, good job!

Positive limit enforcement is nearly there, but a couple of minor tweaks:

- [ ] A notification should be created for the recipient, as it is when a purchase request is blocked due to the seller's balance being too high (see #88).
- [ ] Update text in the message to the credit sender from 'This transfer request cannot be completed, as it would take `recipient username` beyond their outstanding positive credit limit. Please consider following up with them about your intended purchase' to 'This transfer request cannot be completed, as it would take `recipient username` beyond their positive credit limit. `recipient username` has been notified, but please consider following up with them about your intended transfer'.

**Comment by yonasbek** [comment]
@tfwoodroofMCS There are two scenarios that the positive limit occur one is direct balance is too high to receive the transfer second is when the pending purchases or transfer requests that are available in the pending status don't allow the transfer request. So that's why you are seeing that message both messages will be displayed but with different logic. but i can make both off them see the same error message.

**Comment by tfwoodroofMCS** [comment]
Superseded by #202 - marking as Done.
