### ISSUE TITLE
Notifications and wording for positive limit violations for purchase and transfer requests

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#202]
There are two ways to send credit: via a purchase request, and via a transfer request.

At present, each of these can violate the seller/recipient's positive credit limit in one of two ways: either the proposed transaction would take the seller/recipient's balance beyond the limit ('balance only' condition), or it would take the seller/recipient's balance _plus_ the sum of any other outstanding purchase/transfer requests beyond the limit ('balance plus outstanding' condition).

In principle, there are therefore four cases for which behaviour and language needs to be consistent yet distinguishable to the user.

#165 would mean that the 'balance plus outstanding' condition is no longer necessarily blocked, but implementation is a low priority (and it may be desirable to keep the ability to block these transactions in some cases). 

In the meantime, it is therefore necessary to make the following changes:

**Purchase request + balance only:**
- [x] Message to buyer implemented via #86: 'This purchase request cannot be completed, as it would take `seller username 1`, `seller username 2` and `seller username 3` beyond their positive credit limit(s). These seller(s) have been notified, but please consider following up with them about your intended purchase'. No changes needed.
- [x] Notification to relevant seller(s) implemented via #88: '`buyer username` initiated a purchase request with you for `total price` `credit unit`, but this could not be processed as it would have taken you beyond your positive credit limit by `amount` `credit unit`. Please consider following up with `buyer username` about their intended purchase.' No changes needed.

**Transfer request + balance only:**
- [x] Message to sender implemented via #158: 'This transfer request cannot be completed, as it would take `recipient username` beyond their outstanding positive credit limit. Please consider following up with them about your intended purchase.' Needs to be changed to 'This transfer request cannot be completed, as it would take `recipient username` beyond their positive credit limit. `recipient username` has been notified, but please consider following up with them about your intended transfer'. The header also needs to be changed from 'Seller(s) balance too high' to 'Recipient balance too high'. 
- [x] Create notification to recipient: '`sender username` initiated a transfer request with you for `transfer amount` `credit unit`, but this could not be processed as it would have taken you beyond your positive credit limit by `amount` `credit unit`. Please consider following up with `sender username` about their intended transfer.'

**Purchase request + balance plus outstanding:**
- [x] Message to buyer (both text and header) should be the same as for **Purchase request + balance only** (buyer doesn't need to know about outstanding transactions of seller(s)).
- [x] Create notifications to relevant seller(s): '`buyer username` initiated a purchase request with you for `total price` `credit unit`, but this could not be processed as it would have taken your balance plus the sum of your outstanding purchase/transfer requests beyond your positive credit limit by `amount` `credit unit`. Please consider following up with `buyer username` about their intended purchase.' 

**Transfer request + balance plus outstanding:**
- [ ] Message to sender (both text and header) should be same as for **Transfer request + balance only** (sender doesn't need to know about recipient's outstanding transactions).
- [x] Create notification to recipient: '`sender username` initiated a transfer request with you for `transfer amount` `credit unit`, but this could not be processed as it would have taken your balance plus  the sum of your outstanding purchase/transfer requests beyond your positive credit limit by `amount` `credit unit`. Please consider following up with `sender username` about their intended transfer.'

**Comment by tfwoodroofMCS** [comment]
Notification to transfer recipient under **Transfer request + balance only** is incorrect:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/e601f438-6b9a-42fb-91eb-654048b00df6)

Have unchecked the corresponding box.

**Comment by tfwoodroofMCS** [comment]
Testing message to buyer under **Purchase request + balance plus outstanding**, logic is correct but `seller username` appears to be missing:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/07912d62-f96c-4933-91e2-58d7cb41e955)

Have unchecked the corresponding box. Appears to be okay for **Purchase request + balance only**.

**Comment by tfwoodroofMCS** [comment]
Notification to seller under **Purchase request + balance plus outstanding** is incorrect:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/2f077fb0-36f7-42cf-826e-12d99f700056)

Text is correct, but `amount` needs to be calculated as `total price` - (`positive limit` - `balance` - `sum of outstanding purchase/transfer requests`), rather than using the `total price`.

Have unchecked the corresponding box.

**Comment by tfwoodroofMCS** [comment]
Notification to seller for **Purchase request + balance only** sometimes seems to have 'by `amount` `credit unit`' missing from the end of the first sentence:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/308f7031-781b-4d9c-875c-375a49b8a0db)

**Comment by tfwoodroofMCS** [comment]
Recipient notification under **Transfer request + balance plus outstanding** is incorrect:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/43f48ef9-8451-471b-a954-f45e5b30b364)

Text needs to be updated in line with the fact that this is a transfer request (rather than purchase request), and amount needs to be calculated as `transfer amount` - (`positive limit` - `balance` - `sum of outstanding purchase/transfer requests`), rather than using the `transfer amount`.

Have unchecked the corresponding box.

**Comment by tfwoodroofMCS** [comment]
Note: the various `amount` calculations for notifications in the above comments can't be implemented until the notifications table has the functionality to calculate them. For the time being, just implement text changes, but leaving the comments as they are for future reference.
