### ISSUE TITLE
Get Svensk Barter running from this codebase.

### ISSUE THREAD

**Issue by mcsadmin** [CredComSoc/CreditCoopTech#53]
- [x] @EugeneJoe to complete internationalisation
- [x] @tfwoodroofMCS to do final English language review
- [x] @EugeneJoe to create spreadsheet of English and current Swedish to send to Jonas
     - [x] @EugeneJoe to update spreadsheet with Tom's language changes
     - [ ] @tfwoodroofMCS to copy spreadsheet to MCS SB folder
- [x] Jonas to do new Swedish translation
     - [ ] @dilgreen to ask Jonas to add page markers to spreadsheet
- [x] @EugeneJoe to update and push Swedish .json
- [ ] Optional: move cc-node to Render
- [x] @yonasbek & @utunga to deploy Svensk Barter staging (latest code) from Render
- [x] @yonasbek to work on button to switch between languages on staging frontend
- [ ] @EugeneJoe and @yonasbek to import trading data to staging. Will need to do an upgrade of cc-node to 0.8.1.
- [ ] @dilgreen & Jonas to verify that staging is exactly as expected
- [ ] Dil/Jonas to add new categories & images
- [x] Go to paid tier of Render for production if everything works

**Comment by EugeneJoe** [comment]
@tfwoodroofMCS this is done and we are live!

**Comment by tfwoodroofMCS** [comment]
Excellent work @EugeneJoe and @yonasbek!
